site_name: Essence Way of Working
site_description: A complete way of working built on the OMG / SEMAT Essence standard
site_author: Rene Hietkamp
site_url: https://reneh.github.io/essence-way-of-working/

theme:
  name: material

use_directory_urls: false

docs_dir: docs
site_dir: site
