%% State diagram: System (essence-kernel#System)
%% Kernel-alpha; alleen de states die in deze werkwijze daadwerkelijk gebruikt worden
%% zijn gekoppeld aan een activiteit.
stateDiagram-v2
    ArchitectureSelected: Architecture Selected
    Demonstrable: Demonstrable
    Usable: Usable
    Ready: Ready
    Operational: Operational
    Retired: Retired

    [*] --> ArchitectureSelected : Identificeer architectuurbepalende eisen
    [*] --> ArchitectureSelected : Maak low-level design
    ArchitectureSelected --> Demonstrable
    Demonstrable --> Usable : Ondersteun de implementatie
    Usable --> Ready : Bewaak conformance
    Ready --> Operational
    Operational --> Retired
